services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: subscribe_db
      PGDATA: /var/lib/postgresql/data/db
    ports:
      - 5432:5432